# Generated by Django 5.0.6 on 2024-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents a database migration.

    This class is responsible for defining the initial state of the database schema
    and any subsequent changes to the schema.

    Attributes:
        initial (bool): Indicates if this is the initial migration.
        dependencies (list): List of dependencies for this migration.
        operations (list): List of operations to be performed during the migration.
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
