# Generated by Django 5.0.6 on 2024-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents a database migration for altering the video status field.
    """

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('R', 'Real'), ('F', 'Fake')], default='R', max_length=1),
        ),
    ]
